# Generated by Django 4.0.4 on 2022-05-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='boi',
            new_name='bio',
        ),
    ]
